############################################
# Application
############################################

spring.application.name=account-service
server.port=8081

############################################
# MySQL Database
############################################

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/eventledger}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

############################################
# JPA / Hibernate
############################################

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

############################################
# Swagger / OpenAPI
############################################

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

############################################
# Actuator
############################################

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

############################################
# Prometheus
############################################

management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true

############################################
# Logging
############################################

logging.level.root=INFO
logging.level.com.mphasis.assignment=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n